package com.paperscp.sprintometer.config;

public enum ConfiguratorOptions {
    COOLDOWNDELAY,
    STAMINADEDUCTIONDELAY,
    STAMINARESTORATIONDELAY,
    SPRINTDEDUCTIONAMOUNT,
    JUMPDEDUCTIONAMOUNT,
    STAMINARESTORATIONAMOUNT,
    ISENABLED,
    LOWSTAMINAPING
}
